//USERS ACTIONS TYPES
export const USERS_LOADING  = 'USERS_LOADING';
export const USERS_LOADING_OFF = 'USERS_LOADING_OFF'
export const USER_LOGGED_IN  = 'USER_LOGGED_IN';
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const LOGOUT_USER = 'LOGOUT_USER'
//CLASSES ACTIONS TYPES
export const CLASSES_LOADING = 'CLASSES_LOADING'
export const CLASSES_LOADING_OFF = 'CLASSES_LOADING_OFF'
export const GET_ALL_CLASSES = 'GET_ALL_CLASSES';
//TEACHERS ACTIONS TYPES
export const TEACHERS_LOADING = 'TEACHERS_LOADING';
export const TEACHERS_LOADING_OFF = 'TEACHERS_LOADING_OFF';
export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS';
export const GET_SINGLE_TEACHER = 'GET_SINGLE_TEACHER';
//STUDENTS ACTIONS TYPES
export const STUDENTS_LOADING = 'STUDENTS_LOADING';
export const STUDENTS_LOADING_OFF = 'STUDENTS_LOADING_OFF';
export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';
export const GET_SINGLE_STUDENT = 'GET_SINGLE_STUDENT';
//NOTIFICATIONS ACTIONS TYPES
export const NOTIFICATIONS_LOADING = 'NOTIFICATIONS_LOADING';
export const NOTIFICATIONS_LOADING_OFF = 'NOTIFICATIONS_LOADING_OFF';
export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';
export const GET_SINGLE_NOTIFICATION = 'GET_SINGLE_NOTIFICATION';