//USERS ACTIONS TYPES
export const SIGNIN_LOADING  = 'SIGNIN_LOADING';
export const SIGNIN_LOADING_OFF = 'SIGNIN_LOADING_OFF'
export const USER_LOGGED_IN  = 'USER_LOGGED_IN';
export const LOGOUT_USER = 'LOGOUT_USER'
//CLASSES ACTIONS TYPES
export const CLASSES_LOADING = 'CLASSES_LOADING'
export const CLASSES_LOADING_OFF = 'CLASSES_LOADING_OFF'
export const GET_ALL_CLASSES = 'GET_ALL_CLASSES';
export const SET_CLASSES = 'SET_CLASSES';
//TEACHERS ACTIONS TYPES
export const TEACHERS_LOADING = 'TEACHERS_LOADING';
export const TEACHERS_LOADING_OFF = 'TEACHERS_LOADING_OFF';
export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS';
export const GET_SINGLE_TEACHER = 'GET_SINGLE_TEACHER';
export const SET_TEACHERS = 'SET_TEACHERS';